"""
bulk_generate_and_mint.py

Complete pipeline for finishing the L0 (10°x10°) quadrant minting:

  PHASE 1 — for each quadrant in the grid that is NOT yet minted on-chain:
            generate placeholder metadata and pin it to IPFS via the
            backend /ipfs/pin_json endpoint.
  PHASE 2 — batch-mint all quadrants that have a CID but are not yet minted.

Resumable: progress is saved to quadrant_mint_progress.json, so if the script
is interrupted (RPC error, terminal closed, etc.), the next run continues from
where it left off — nothing is pinned or minted twice.

Required ENV variables:
    AMOY_RPC_URL                  - Polygon Amoy RPC URL
    BACKEND_WALLET_PRIVATE_KEY    - backend wallet private key (must hold MINTER_ROLE)

Optional ENV variables:
    GEOQUADRANTS_ADDRESS   - default: current GeoQuadrants contract address
    FFT_API_BASE           - default: http://localhost:8000 (FastAPI backend)

Usage:
    python bulk_generate_and_mint.py
"""

import os
import json
import time
import requests
from web3 import Web3
from web3.middleware import ExtraDataToPOAMiddleware
from global_land_mask import globe  # pip install global-land-mask --break-system-packages

# ── CONFIG ────────────────────────────────────────────────────────────────
RPC_URL = os.getenv("AMOY_RPC_URL", "")
PRIVATE_KEY = os.getenv("BACKEND_WALLET_PRIVATE_KEY", "")
CONTRACT_ADDRESS = os.getenv("GEOQUADRANTS_ADDRESS", "0x1421C0dd6D962fb5c5A29340C74bEE66AdA60BFb")
ABI_PATH = "abi/GeoQuadrants.json"
API_BASE = os.getenv("FFT_API_BASE", "http://localhost:8000")

PROGRESS_FILE = "quadrant_mint_progress.json"
CHUNK_SIZE = 40          # quadrants per batch-mint transaction
CHAIN_ID = 80002         # Polygon Amoy

# Set to False to exclude the lon=180 duplicate edge (lon=180 == lon=-180)
INCLUDE_LON_180_DUPLICATE = True

# ── Land-only filter ─────────────────────────────────────────────────────
LAND_ONLY = True          # ✅ skip purely oceanic quadrants
LAND_SAMPLE_GRID = 5      # NxN sample points within each 10°x10° quadrant
LAND_MIN_SAMPLES = 1      # minimum sample points that must be "land" for the quadrant to pass
                           # (1 = include coastal/island quadrants where only a small part is land)


def is_land_quadrant(lat0, lon0, step=10, n=LAND_SAMPLE_GRID, min_hits=LAND_MIN_SAMPLES):
    """
    Samples NxN points within the quadrant [lat0, lat0+step] x [lon0, lon0+step]
    and returns True if at least `min_hits` points are on land (includes coastal
    and island quadrants where only part of the territory is land).
    """
    hits = 0
    for i in range(n):
        lat = lat0 + (step * i) / (n - 1) if n > 1 else lat0
        lat = min(lat, 90.0)
        for j in range(n):
            lon = lon0 + (step * j) / (n - 1) if n > 1 else lon0
            lon = ((lon + 180) % 360) - 180  # normalise to [-180, 180)
            if globe.is_land(lat, lon):
                hits += 1
                if hits >= min_hits:
                    return True
    return hits >= min_hits


# ── Grid generation (1:1 replica of l0CellIdFromLatLon10deg from web3Config.js) ─
def build_grid():
    quadrants = []
    skipped_ocean = 0
    lon_range = range(37) if INCLUDE_LON_180_DUPLICATE else range(36)
    for lat_idx in range(17):            # 0..16  ->  lat -80..80
        lat = -80 + lat_idx * 10
        for lon_idx in lon_range:        # 0..36  ->  lon -180..180
            lon = -180 + lon_idx * 10
            cell_id = lat_idx * 1000 + lon_idx
            token_id = cell_id            # resolution=0 -> tokenId = cellId

            if LAND_ONLY and not is_land_quadrant(lat, lon):
                skipped_ocean += 1
                continue

            quadrants.append({
                "lat": lat,
                "lon": lon,
                "latIdx": lat_idx,
                "lonIdx": lon_idx,
                "cellId": cell_id,
                "tokenId": token_id,
            })

    if LAND_ONLY:
        print(f"Land-only filter: {skipped_ocean} oceanic quadrants skipped.")

    return quadrants


# ── Progress cache (resumable) ──────────────────────────────────────────────
def load_progress():
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE) as f:
            return json.load(f)
    return {}


def save_progress(progress):
    with open(PROGRESS_FILE, "w") as f:
        json.dump(progress, f, indent=2)


# ── Metadata generation (placeholder — owner can update after claiming) ────
def build_metadata(q):
    """
    Same structure as the one generated by the QuadrantEditor modal when a user
    manually edits a quadrant (regionType/environment/historicalData/population/
    infrastructure), but with placeholder values while the quadrant awaits
    a new owner to claim and fill it with real data.
    """
    return {
        "name": f"FfT Quadrant ({q['lat']}°, {q['lon']}°)",
        "description": (
            "Unclaimed 10°x10° geographic quadrant in the Framework for "
            "Trust registry. Owner can update metadata after claiming "
            "ownership."
        ),
        "attributes": {
            "regionType": "Unknown",
            "environment": None,
            "historicalData": None,
            "population": None,
            "infrastructure": None,
            "lastUpdated": None,
        },
    }


def pin_metadata(metadata):
    resp = requests.post(
        f"{API_BASE}/ipfs/pin_json",
        json={"json": metadata, "name": metadata["name"]},
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    cid = data.get("cid") or data.get("ipfsHash") or data.get("IpfsHash")
    if not cid:
        raise RuntimeError(f"Backend did not return a CID: {data}")
    return cid


def main():
    if not RPC_URL or not PRIVATE_KEY:
        raise SystemExit(
            "Set AMOY_RPC_URL and BACKEND_WALLET_PRIVATE_KEY environment variables."
        )

    grid = build_grid()
    print(f"Total quadrants in grid: {len(grid)}")

    progress = load_progress()

    w3 = Web3(Web3.HTTPProvider(RPC_URL))
    w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)
    if not w3.is_connected():
        raise SystemExit("Cannot connect to RPC. Check AMOY_RPC_URL.")

    with open(ABI_PATH) as f:
        abi = json.load(f)
    contract = w3.eth.contract(
        address=Web3.to_checksum_address(CONTRACT_ADDRESS), abi=abi
    )

    account = w3.eth.account.from_key(PRIVATE_KEY)
    backend_wallet = account.address

    minter_role = contract.functions.MINTER_ROLE().call()
    if not contract.functions.hasRole(minter_role, backend_wallet).call():
        raise SystemExit(f"Wallet {backend_wallet} does not have MINTER_ROLE.")

    # ── PHASE 1 — pin metadata for all quadrants without a CID ─────────────
    to_pin = []
    for q in grid:
        key = f"{q['latIdx']}_{q['lonIdx']}"
        entry = progress.get(key, {})
        if entry.get("cid"):
            continue
        if contract.functions.exists(q["tokenId"]).call():
            progress[key] = {"minted": True}
            continue
        to_pin.append((key, q))

    print(f"To pin on IPFS: {len(to_pin)}")

    for i, (key, q) in enumerate(to_pin):
        metadata = build_metadata(q)
        try:
            cid = pin_metadata(metadata)
            progress[key] = {"cid": cid, "minted": False}
            print(f"  [{i + 1}/{len(to_pin)}] {q['lat']:>4},{q['lon']:>4} -> {cid}")
        except Exception as e:
            print(f"  [{i + 1}/{len(to_pin)}] ERROR {q['lat']},{q['lon']}: {e}")

        if (i + 1) % 20 == 0:
            save_progress(progress)

    save_progress(progress)

    # ── PHASE 2 — batch mint all quadrants that have a CID but are not minted ─
    to_mint = []
    for q in grid:
        key = f"{q['latIdx']}_{q['lonIdx']}"
        entry = progress.get(key, {})
        if entry.get("cid") and not entry.get("minted"):
            to_mint.append((key, q, entry["cid"]))

    print(f"To mint: {len(to_mint)}")

    nonce = w3.eth.get_transaction_count(backend_wallet)

    for i in range(0, len(to_mint), CHUNK_SIZE):
        chunk = to_mint[i:i + CHUNK_SIZE]

        lats = [c[1]["lat"] for c in chunk]
        lons = [c[1]["lon"] for c in chunk]
        resolutions = [0 for _ in chunk]
        cell_ids = [c[1]["cellId"] for c in chunk]
        metadata_hashes = [f"ipfs://{c[2]}" for c in chunk]

        try:
            gas_est = contract.functions.batchMintQuadrants(
                backend_wallet, lats, lons, resolutions, cell_ids, metadata_hashes
            ).estimate_gas({"from": backend_wallet})
            gas_limit = int(gas_est * 1.2)  # 20% buffer
        except Exception as e:
            print(f"  estimate_gas failed for batch {i}: {e} — using fallback")
            gas_limit = 300_000 * len(chunk)

        tx = contract.functions.batchMintQuadrants(
            backend_wallet, lats, lons, resolutions, cell_ids, metadata_hashes
        ).build_transaction({
            "from": backend_wallet,
            "nonce": nonce,
            "gas": gas_limit,
            "maxFeePerGas": w3.to_wei("50", "gwei"),
            "maxPriorityFeePerGas": w3.to_wei("30", "gwei"),
            "chainId": CHAIN_ID,
        })

        signed = w3.eth.account.sign_transaction(tx, PRIVATE_KEY)
        tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

        status = "OK" if receipt.status == 1 else "REVERT"
        print(
            f"Batch {i // CHUNK_SIZE + 1}: {len(chunk)} quadrants, "
            f"gas_limit={gas_limit}, gas_used={receipt.gasUsed}, "
            f"tx={tx_hash.hex()}, status={status}"
        )

        if receipt.status == 1:
            for key, q, cid in chunk:
                progress[key]["minted"] = True
            save_progress(progress)
        else:
            print("  Batch reverted — progress NOT marked as minted, "
                  "next run will retry.")

        nonce += 1
        time.sleep(1)

    minted_count = sum(1 for v in progress.values() if v.get("minted"))
    print(f"\nDone. Total minted (including previous runs): {minted_count}/{len(grid)}")


if __name__ == "__main__":
    main()
